# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from ondewo.nlu.session_pb2 import (
    DetectIntentResponse as ondewo___nlu___session_pb2___DetectIntentResponse,
)

from ondewo.t2s.text_to_speech_pb2 import (
    SynthesizeResponse as ondewo___t2s___text_to_speech_pb2___SynthesizeResponse,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode

class S2sStreamRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    audio = ...  # type: builtin___bytes
    session_id = ...  # type: typing___Text
    end_of_stream = ...  # type: builtin___bool
    def __init__(
        self,
        *,
        audio: typing___Optional[builtin___bytes] = None,
        session_id: typing___Optional[typing___Text] = None,
        end_of_stream: typing___Optional[builtin___bool] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> S2sStreamRequest: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> S2sStreamRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "audio", b"audio", "end_of_stream", b"end_of_stream", "session_id", b"session_id"
        ],
    ) -> None: ...

global___S2sStreamRequest = S2sStreamRequest

class S2sStreamResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def detect_intent_response(self) -> ondewo___nlu___session_pb2___DetectIntentResponse: ...
    @property
    def synthetize_response(self) -> ondewo___t2s___text_to_speech_pb2___SynthesizeResponse: ...
    def __init__(
        self,
        *,
        detect_intent_response: typing___Optional[ondewo___nlu___session_pb2___DetectIntentResponse] = None,
        synthetize_response: typing___Optional[ondewo___t2s___text_to_speech_pb2___SynthesizeResponse] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> S2sStreamResponse: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> S2sStreamResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "detect_intent_response", b"detect_intent_response", "synthetize_response", b"synthetize_response"
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "detect_intent_response", b"detect_intent_response", "synthetize_response", b"synthetize_response"
        ],
    ) -> None: ...

global___S2sStreamResponse = S2sStreamResponse
