# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ondewo/csi/conversation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ondewo.nlu import session_pb2 as ondewo_dot_nlu_dot_session__pb2
from ondewo.t2s import text_to_speech_pb2 as ondewo_dot_t2s_dot_text__to__speech__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="ondewo/csi/conversation.proto",
    package="ondewo.csi",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1dondewo/csi/conversation.proto\x12\nondewo.csi\x1a\x18ondewo/nlu/session.proto\x1a\x1fondewo/t2s/text-to-speech.proto"L\n\x10S2sStreamRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x15\n\rend_of_stream\x18\x03 \x01(\x08"\x92\x01\n\x11S2sStreamResponse\x12@\n\x16\x64\x65tect_intent_response\x18\x01 \x01(\x0b\x32 .ondewo.nlu.DetectIntentResponse\x12;\n\x13synthetize_response\x18\x02 \x01(\x0b\x32\x1e.ondewo.t2s.SynthesizeResponse2_\n\rConversations\x12N\n\tS2sStream\x12\x1c.ondewo.csi.S2sStreamRequest\x1a\x1d.ondewo.csi.S2sStreamResponse"\x00(\x01\x30\x01\x62\x06proto3',
    dependencies=[
        ondewo_dot_nlu_dot_session__pb2.DESCRIPTOR,
        ondewo_dot_t2s_dot_text__to__speech__pb2.DESCRIPTOR,
    ],
)


_S2SSTREAMREQUEST = _descriptor.Descriptor(
    name="S2sStreamRequest",
    full_name="ondewo.csi.S2sStreamRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="audio",
            full_name="ondewo.csi.S2sStreamRequest.audio",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="session_id",
            full_name="ondewo.csi.S2sStreamRequest.session_id",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="end_of_stream",
            full_name="ondewo.csi.S2sStreamRequest.end_of_stream",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=104,
    serialized_end=180,
)


_S2SSTREAMRESPONSE = _descriptor.Descriptor(
    name="S2sStreamResponse",
    full_name="ondewo.csi.S2sStreamResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="detect_intent_response",
            full_name="ondewo.csi.S2sStreamResponse.detect_intent_response",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="synthetize_response",
            full_name="ondewo.csi.S2sStreamResponse.synthetize_response",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=183,
    serialized_end=329,
)

_S2SSTREAMRESPONSE.fields_by_name[
    "detect_intent_response"
].message_type = ondewo_dot_nlu_dot_session__pb2._DETECTINTENTRESPONSE
_S2SSTREAMRESPONSE.fields_by_name[
    "synthetize_response"
].message_type = ondewo_dot_t2s_dot_text__to__speech__pb2._SYNTHESIZERESPONSE
DESCRIPTOR.message_types_by_name["S2sStreamRequest"] = _S2SSTREAMREQUEST
DESCRIPTOR.message_types_by_name["S2sStreamResponse"] = _S2SSTREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

S2sStreamRequest = _reflection.GeneratedProtocolMessageType(
    "S2sStreamRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _S2SSTREAMREQUEST,
        "__module__": "ondewo.csi.conversation_pb2"
        # @@protoc_insertion_point(class_scope:ondewo.csi.S2sStreamRequest)
    },
)
_sym_db.RegisterMessage(S2sStreamRequest)

S2sStreamResponse = _reflection.GeneratedProtocolMessageType(
    "S2sStreamResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _S2SSTREAMRESPONSE,
        "__module__": "ondewo.csi.conversation_pb2"
        # @@protoc_insertion_point(class_scope:ondewo.csi.S2sStreamResponse)
    },
)
_sym_db.RegisterMessage(S2sStreamResponse)


_CONVERSATIONS = _descriptor.ServiceDescriptor(
    name="Conversations",
    full_name="ondewo.csi.Conversations",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=331,
    serialized_end=426,
    methods=[
        _descriptor.MethodDescriptor(
            name="S2sStream",
            full_name="ondewo.csi.Conversations.S2sStream",
            index=0,
            containing_service=None,
            input_type=_S2SSTREAMREQUEST,
            output_type=_S2SSTREAMRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_CONVERSATIONS)

DESCRIPTOR.services_by_name["Conversations"] = _CONVERSATIONS

# @@protoc_insertion_point(module_scope)
