# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.struct_pb2 import (
    Struct as google___protobuf___struct_pb2___Struct,
)

from google.rpc.status_pb2 import (
    Status as google___rpc___status_pb2___Status,
)

from ondewo.nlu.session_pb2 import (
    DetectIntentResponse as ondewo___nlu___session_pb2___DetectIntentResponse,
)

from ondewo.t2s.text_to_speech_pb2 import (
    SynthesizeResponse as ondewo___t2s___text_to_speech_pb2___SynthesizeResponse,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    Union as typing___Union,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class ControlStatus(builtin___int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> 'ControlStatus': ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List['ControlStatus']: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, 'ControlStatus']]: ...
    OK = typing___cast('ControlStatus', 0)
    EMERGENCY_STOP = typing___cast('ControlStatus', 1)
OK = typing___cast('ControlStatus', 0)
EMERGENCY_STOP = typing___cast('ControlStatus', 1)
global___ControlStatus = ControlStatus

class S2sPipeline(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: typing___Text
    s2t_pipeline_id = ... # type: typing___Text
    nlu_project_id = ... # type: typing___Text
    nlu_language_code = ... # type: typing___Text
    t2s_pipeline_id = ... # type: typing___Text

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        s2t_pipeline_id : typing___Optional[typing___Text] = None,
        nlu_project_id : typing___Optional[typing___Text] = None,
        nlu_language_code : typing___Optional[typing___Text] = None,
        t2s_pipeline_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> S2sPipeline: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> S2sPipeline: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id",u"nlu_language_code",b"nlu_language_code",u"nlu_project_id",b"nlu_project_id",u"s2t_pipeline_id",b"s2t_pipeline_id",u"t2s_pipeline_id",b"t2s_pipeline_id"]) -> None: ...
global___S2sPipeline = S2sPipeline

class S2sPipelineId(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: typing___Text

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> S2sPipelineId: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> S2sPipelineId: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id"]) -> None: ...
global___S2sPipelineId = S2sPipelineId

class ListS2sPipelinesRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ListS2sPipelinesRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ListS2sPipelinesRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
global___ListS2sPipelinesRequest = ListS2sPipelinesRequest

class ListS2sPipelinesResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def pipelines(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[global___S2sPipeline]: ...

    def __init__(self,
        *,
        pipelines : typing___Optional[typing___Iterable[global___S2sPipeline]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ListS2sPipelinesResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ListS2sPipelinesResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"pipelines",b"pipelines"]) -> None: ...
global___ListS2sPipelinesResponse = ListS2sPipelinesResponse

class S2sStreamRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    pipeline_id = ... # type: typing___Text
    session_id = ... # type: typing___Text
    audio = ... # type: builtin___bytes
    end_of_stream = ... # type: builtin___bool
    initial_intent_display_name = ... # type: typing___Text

    def __init__(self,
        *,
        pipeline_id : typing___Optional[typing___Text] = None,
        session_id : typing___Optional[typing___Text] = None,
        audio : typing___Optional[builtin___bytes] = None,
        end_of_stream : typing___Optional[builtin___bool] = None,
        initial_intent_display_name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> S2sStreamRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> S2sStreamRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"audio",b"audio",u"end_of_stream",b"end_of_stream",u"initial_intent_display_name",b"initial_intent_display_name",u"pipeline_id",b"pipeline_id",u"session_id",b"session_id"]) -> None: ...
global___S2sStreamRequest = S2sStreamRequest

class S2sStreamResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def detect_intent_response(self) -> ondewo___nlu___session_pb2___DetectIntentResponse: ...

    @property
    def synthetize_response(self) -> ondewo___t2s___text_to_speech_pb2___SynthesizeResponse: ...

    @property
    def sip_trigger(self) -> global___SipTrigger: ...

    def __init__(self,
        *,
        detect_intent_response : typing___Optional[ondewo___nlu___session_pb2___DetectIntentResponse] = None,
        synthetize_response : typing___Optional[ondewo___t2s___text_to_speech_pb2___SynthesizeResponse] = None,
        sip_trigger : typing___Optional[global___SipTrigger] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> S2sStreamResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> S2sStreamResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"detect_intent_response",b"detect_intent_response",u"response",b"response",u"sip_trigger",b"sip_trigger",u"synthetize_response",b"synthetize_response"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"detect_intent_response",b"detect_intent_response",u"response",b"response",u"sip_trigger",b"sip_trigger",u"synthetize_response",b"synthetize_response"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"response",b"response"]) -> typing_extensions___Literal["detect_intent_response","synthetize_response","sip_trigger"]: ...
global___S2sStreamResponse = S2sStreamResponse

class SipTrigger(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class SipTriggerType(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'SipTrigger.SipTriggerType': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['SipTrigger.SipTriggerType']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'SipTrigger.SipTriggerType']]: ...
        UNSPECIFIED = typing___cast('SipTrigger.SipTriggerType', 0)
        HANGUP = typing___cast('SipTrigger.SipTriggerType', 1)
        HUMAN_HANDOVER = typing___cast('SipTrigger.SipTriggerType', 2)
        SEND_NOW = typing___cast('SipTrigger.SipTriggerType', 3)
        PAUSE = typing___cast('SipTrigger.SipTriggerType', 4)
    UNSPECIFIED = typing___cast('SipTrigger.SipTriggerType', 0)
    HANGUP = typing___cast('SipTrigger.SipTriggerType', 1)
    HUMAN_HANDOVER = typing___cast('SipTrigger.SipTriggerType', 2)
    SEND_NOW = typing___cast('SipTrigger.SipTriggerType', 3)
    PAUSE = typing___cast('SipTrigger.SipTriggerType', 4)
    global___SipTriggerType = SipTriggerType

    type = ... # type: global___SipTrigger.SipTriggerType

    @property
    def content(self) -> google___protobuf___struct_pb2___Struct: ...

    def __init__(self,
        *,
        type : typing___Optional[global___SipTrigger.SipTriggerType] = None,
        content : typing___Optional[google___protobuf___struct_pb2___Struct] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> SipTrigger: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> SipTrigger: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"content",b"content"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content",b"content",u"type",b"type"]) -> None: ...
global___SipTrigger = SipTrigger

class CheckUpstreamHealthResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def s2t_status(self) -> google___rpc___status_pb2___Status: ...

    @property
    def nlu_status(self) -> google___rpc___status_pb2___Status: ...

    @property
    def t2s_status(self) -> google___rpc___status_pb2___Status: ...

    def __init__(self,
        *,
        s2t_status : typing___Optional[google___rpc___status_pb2___Status] = None,
        nlu_status : typing___Optional[google___rpc___status_pb2___Status] = None,
        t2s_status : typing___Optional[google___rpc___status_pb2___Status] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> CheckUpstreamHealthResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> CheckUpstreamHealthResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"nlu_status",b"nlu_status",u"s2t_status",b"s2t_status",u"t2s_status",b"t2s_status"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"nlu_status",b"nlu_status",u"s2t_status",b"s2t_status",u"t2s_status",b"t2s_status"]) -> None: ...
global___CheckUpstreamHealthResponse = CheckUpstreamHealthResponse

class ControlStreamRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ControlStreamRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ControlStreamRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
global___ControlStreamRequest = ControlStreamRequest

class ControlStreamResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    control_status = ... # type: global___ControlStatus

    def __init__(self,
        *,
        control_status : typing___Optional[global___ControlStatus] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ControlStreamResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ControlStreamResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"control_status",b"control_status"]) -> None: ...
global___ControlStreamResponse = ControlStreamResponse

class SetControlStatusRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    control_status = ... # type: global___ControlStatus

    def __init__(self,
        *,
        control_status : typing___Optional[global___ControlStatus] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> SetControlStatusRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> SetControlStatusRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"control_status",b"control_status"]) -> None: ...
global___SetControlStatusRequest = SetControlStatusRequest

class SetControlStatusResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    old_control_status = ... # type: global___ControlStatus
    new_control_status = ... # type: global___ControlStatus

    def __init__(self,
        *,
        old_control_status : typing___Optional[global___ControlStatus] = None,
        new_control_status : typing___Optional[global___ControlStatus] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> SetControlStatusResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> SetControlStatusResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"new_control_status",b"new_control_status",u"old_control_status",b"old_control_status"]) -> None: ...
global___SetControlStatusResponse = SetControlStatusResponse
